# Values for Kubeflow deployment mode - Exact Kustomize parity
deploymentMode: kubeflow

# Override chart name to match Kustomize naming
nameOverride: "notebook-controller"

global:
  namespace: kubeflow
  imageRegistry: ghcr.io/kubeflow/kubeflow
  imageTag: v1.10.0

# Common labels exactly matching Kustomize
commonLabels:
  app: notebook-controller
  kustomize.component: notebook-controller

controller:
  config:
    useIstio: true
    istioGateway: "kubeflow/kubeflow-gateway"
    istioHost: "*"
    clusterDomain: "cluster.local"
    enableCulling: false
    cullIdleTime: "1440"
    idlenessCheckPeriod: "1"
  
  manager:
    enableLeaderElection: true
    metricsAddr: "127.0.0.1:8080"
    healthProbeAddr: ":8081"
  
  # Enable auth proxy for metrics protection in Kubeflow
  authProxy:
    enabled: true
    image:
      registry: quay.io
      repository: brancz/kube-rbac-proxy
      tag: v0.4.0
  
  # Webhook server disabled by default (matches Kustomize)
  webhook:
    enabled: false
  
  # Security context matching Kustomize
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  
  securityContext:
    runAsNonRoot: true
    allowPrivilegeEscalation: false
    runAsUser: 1000
    capabilities:
      drop:
      - ALL

# Enable main service (matches manager/service.yaml)
service:
  enabled: true
  type: ClusterIP
  port: 443

# Enable metrics service for Prometheus scraping (matches auth_proxy_service.yaml)
metricsService:
  enabled: true
  annotations:
    prometheus.io/port: "8443"
    prometheus.io/scheme: https
    prometheus.io/scrape: "true"
  labels:
    control-plane: controller-manager

# RBAC exactly matching Kustomize
rbac:
  create: true
  serviceAccount:
    create: true
    name: ""  # Will be auto-generated to match Kustomize naming
  authProxy:
    enabled: true
  leaderElection:
    enabled: true

# Enable monitoring with proper annotations
monitoring:
  enabled: true
  prometheus:
    enabled: true

# CRD management with patches
crds:
  install: true
  validationPatches:
    enabled: true

# Kustomize compatibility for Kubeflow
kustomizeMode:
  enabled: true
  useOriginalLabels: true
  useOriginalNames: true

# Disable samples in production Kubeflow
samples:
  enabled: false