# Values for standalone deployment mode - Exact Kustomize parity
deploymentMode: standalone

global:
  namespace: notebook-controller-system
  imageRegistry: ghcr.io/kubeflow/kubeflow
  imageTag: v1.10.0

# Common labels exactly matching Kustomize default
commonLabels:
  app: notebook-controller
  kustomize.component: notebook-controller

controller:
  config:
    useIstio: false
    clusterDomain: "cluster.local"
    enableCulling: false
    cullIdleTime: "1440"
    idlenessCheckPeriod: "1"
  
  manager:
    enableLeaderElection: true
    metricsAddr: "0.0.0.0:8080"  # Expose metrics directly in standalone mode
    healthProbeAddr: ":8081"
  
  # Disable auth proxy in standalone mode (matches Kustomize default)
  authProxy:
    enabled: false
  
  # Webhook disabled by default (matches Kustomize)
  webhook:
    enabled: false
  
  # Security context matching Kustomize
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  
  securityContext:
    runAsNonRoot: true
    allowPrivilegeEscalation: false
    runAsUser: 1000
    capabilities:
      drop:
      - ALL

# Enable main service (matches manager/service.yaml)  
service:
  enabled: true
  type: ClusterIP
  port: 443

# Disable metrics service in standalone (no auth proxy)
metricsService:
  enabled: false

# RBAC exactly matching Kustomize
rbac:
  create: true
  serviceAccount:
    create: true
    name: ""  # Will be auto-generated
  authProxy:
    enabled: false  # No auth proxy in standalone
  leaderElection:
    enabled: true

# Enable direct metrics without auth proxy
monitoring:
  enabled: true
  prometheus:
    enabled: true
    podAnnotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "8080"
      prometheus.io/path: "/metrics"

# CRD management with patches
crds:
  install: true
  validationPatches:
    enabled: true

# Use exact Kustomize naming in standalone mode
kustomizeMode:
  enabled: true
  useOriginalLabels: true
  useOriginalNames: true

# Enable samples for testing in standalone mode
samples:
  enabled: true
  namespace: "default"